In [1]:
import numpy as np

In [4]:
A = np.empty((2,3), dtype=np.float64)
A

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
B = np.eye(4,6,4)
B

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
C = np.random.randint(-10, 10,(3,3))
C

array([[-7,  0,  5],
       [ 6,  0,  4],
       [ 1,  9, -3]])

In [14]:
np.diag(C)

array([-7,  0, -3])

In [16]:
A = np.random.randint(-10, 10, (4,4))
A

array([[ -7,  -2,  -9,   2],
       [  4,  -5,   9,  -4],
       [-10, -10,   3,   8],
       [  8,   7,   6,  -5]])

In [23]:
A[0,3] = 0
D = np.triu(A, -1)
print(D)
C = np.triu(A, -1) + np.tril(A, 1) - A
C

[[ -7  -2  -9   0]
 [  4  -5   9  -4]
 [  0 -10   3   8]
 [  0   0   6  -5]]


array([[ -7,  -2,   0,   0],
       [  4,  -5,   9,   0],
       [  0, -10,   3,   8],
       [  0,   0,   6,  -5]])

In [24]:
A = np.array([[1,2,-3], [4,1,5]])
B = np.random.randint(-10, 10, (3,3))
print(A)
print(B)

[[ 1  2 -3]
 [ 4  1  5]]
[[-7  6 -4]
 [ 3  0  7]
 [-8 -9  8]]


In [26]:
A@B

array([[ 23,  33, -14],
       [-65, -21,  31]])

In [28]:
A = np.random.randint(-10,10,(3,3))
A

array([[ 8,  5,  6],
       [ 1, -2,  0],
       [-8, -2,  3]])

In [29]:
np.linalg.matrix_power(A,2)

array([[ 21,  18,  66],
       [  6,   9,   6],
       [-90, -42, -39]])

In [31]:
np.linalg.det(A)
np.linalg.matrix_rank(A)

3

In [34]:
# Thuật toán phân tích ma trận
X = np.array([[5,3,0,1],[4,0,0,1],[1,1,0,5],[1,0,0,4],[0,1,5,4]])
X

array([[5, 3, 0, 1],
       [4, 0, 0, 1],
       [1, 1, 0, 5],
       [1, 0, 0, 4],
       [0, 1, 5, 4]])

In [37]:
# Khoi tao gia tri xuat phat W, H
m,n = X.shape
print(m,n)
W = np.random.random((m,2))
H = np.random.random((n,2))
print(W)
print(H)

5 4
[[0.38534655 0.92504502]
 [0.71658292 0.88833973]
 [0.21912414 0.83285005]
 [0.9919599  0.28810586]
 [0.13471281 0.69604019]]
[[0.01539614 0.33219392]
 [0.01824524 0.91448334]
 [0.32955247 0.30726036]
 [0.8740239  0.88826943]]


In [38]:
steps = 1000
beta = 0.001
L0 = 1e-5
for step in range(steps): # Loop steps times
    L = 0
    for u in range(m):
        for i in range(n):
            if X[u,i] > 0:
                eui = X[u,i] - W[u,:]@H[i,:]
                for k in range(2):
                    W[u, k] = W[u,k] + beta*2*eui*H[i,k]
                    H[i, k] = H[i,k] + beta*2*eui*W[u,k]
                eui_new = X[u, i] - W[u,:]@H[i,:]
                L = L + eui_new**2
    if L < L0:
        break
# print the result
print("Step:", step)
print(W)
print(H)
print(W@H.T)
print(X)

Step: 999
[[-0.29653187  2.32622417]
 [-0.14645351  1.85728794]
 [ 1.92568432  0.97905993]
 [ 1.52958062  0.81509973]
 [ 1.39655567  1.32011422]]
[[-0.49783805  2.09873115]
 [-0.22728233  1.22549027]
 [ 1.43067295  2.20137572]
 [ 2.22905769  0.71121824]]
[[5.02974397 2.91816154 4.69665329 0.99346642]
 [3.97085818 2.30937459 3.87906151 0.99448374]
 [1.09610464 0.7621544  4.91030321 4.98878672]
 [0.94919177 0.65125015 3.98267039 3.98923725]
 [2.07530627 1.30037471 4.9040818  4.05189247]]
[[5 3 0 1]
 [4 0 0 1]
 [1 1 0 5]
 [1 0 0 4]
 [0 1 5 4]]
