In [1]:
import numpy as np

### Một số câu lệnh
> np.inner(x,y) : tính tích vô hướng giữa hai vecto

> np.linalg.norm(x): tính chuẩn của vecto

In [5]:
# Tinh tich vo huong
a = np.array([2,-4,3,2,1])
b = np.array([-1,5,2,-6,0])
print(a)
print(b)
np.inner(a, b) # tinh tich vo huong

# Tinh chuan
print("Do dai a:", np.linalg.norm(a))
print("Do dai b:", np.linalg.norm(b))

[ 2 -4  3  2  1]
[-1  5  2 -6  0]
Do dai a: 5.830951894845301
Do dai b: 8.12403840463596


In [6]:
a@b
np.dot(a, b)
np.matmul(a, b)

-28

In [8]:
# khoang cach giua 2 vecto
print("The distance between a and b is:", np.linalg.norm(a - b))

The distance between a and b is: 12.489995996796797


In [9]:
# khoang cach giua a va b
cos_w = np.inner(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
print(cos_w)

-0.5910804632890486


### Xây dựng cơ sở trực giao, trực chuẩn của không gian


In [20]:
# Chon 4 vector
x1 = np.array([1,1,1,1])
x2 = np.array([-1,2,2,1])
x3 = np.array([0,-2,4,2])
x4 = np.array([2,5,-1,3])
# Kiem tra he vecto co phai co so hay khong.

x = np.vstack([x1, x2, x3, x4]).T
r = np.linalg.matrix_rank(x) # r = 4 thi la co so.
if r == 4:
    print("He duoc chon la 1 co so.")
else:
    print("Day khong phai la co so.")

# Truc giao hoa 
v1 = x1
v2 = x2 - np.inner(x2, v1)/np.inner(v1, v1) * v1
v3 = x3 - np.inner(x3, v1)/np.inner(v1, v1) * v1 - np.inner(x3, v2)/np.inner(v2, v2) * v2
v4 = x4 - np.inner(x4, v1)/np.inner(v1, v1) * v1 - np.inner(x4, v2)/np.inner(v2, v2) * v2 - \
np.inner(x4, v3)/np.inner(v3, v3) * v3
print(v1, v2, v3, v4, sep="\n")

# Kiem tra bang cach tinh tich tung doi mot, neu tat ca = 0 thi dung.
# Truc chuan hoa
e_v1 = v1/np.linalg.norm(v1) 
e_v2 = v2/np.linalg.norm(v2) 
e_v3 = v3/np.linalg.norm(v3) 
e_v4 = v4/np.linalg.norm(v4)
print(e_v1, e_v2, e_v3, e_v4, sep="\n")
np.linalg.norm(e_v2)



He duoc chon la 1 co so.
[1 1 1 1]
[-2.  1.  1.  0.]
[-0.33333333 -3.33333333  2.66666667  1.        ]
[-0.54310345 -0.18103448 -0.90517241  1.62931034]
[0.5 0.5 0.5 0.5]
[-0.81649658  0.40824829  0.40824829  0.        ]
[-0.0758098  -0.75809804  0.60647843  0.22742941]
[-0.27854301 -0.09284767 -0.46423835  0.83562902]


1.0

In [25]:
# Tinh toạ độ của các vector trong cơ sở trực giao, trực chuẩn
x = np.array([7, -12,2,4])
print(x)
print(f"Toa do cua {x} trong co so truc giao v: ")
x_v = np.array([np.inner(x, v1)/np.inner(v1, v1), np.inner(x, v2)/np.inner(v2, v2),
               np.inner(x, v3)/np.inner(v3, v3), np.inner(x, v4)/np.inner(v4, v4)])
print(x_v)
e_v = np.array([np.inner(x, e_v1), np.inner(x, e_v2),
               np.inner(x, e_v3), np.inner(x, e_v4)])
print(e_v)

[  7 -12   2   4]
Toa do cua [  7 -12   2   4] trong co so truc giao v: 
[ 0.25       -4.          2.43103448  0.80952381]
[ 0.5        -9.79795897 10.68918241  1.57841037]


In [28]:
# tinh toa do bang giai phuong trinh: B[x]_B = x
EV = np.vstack([e_v1, e_v2, e_v3, e_v4]).T
print(EV)
np.linalg.solve(EV, x)

[[ 0.5        -0.81649658 -0.0758098  -0.27854301]
 [ 0.5         0.40824829 -0.75809804 -0.09284767]
 [ 0.5         0.40824829  0.60647843 -0.46423835]
 [ 0.5         0.          0.22742941  0.83562902]]


array([ 0.5       , -9.79795897, 10.68918241,  1.57841037])

### Tim hinh chieu truc giao cua 1 vecto


In [38]:
# Xét R4, cho không gian W có cơ sở:
x1 = np.array([1,1,1,1])
x2 = np.array([-1,2,2,1])
x3 = np.array([0,-2,4,2])

x = np.vstack([x1, x2, x3, x4]).T

# Truc giao hoa 
v1 = x1
v2 = x2 - np.inner(x2, v1)/np.inner(v1, v1) * v1
v3 = x3 - np.inner(x3, v1)/np.inner(v1, v1) * v1 - np.inner(x3, v2)/np.inner(v2, v2) * v2


# Kiem tra bang cach tinh tich tung doi mot, neu tat ca = 0 thi dung.
# Truc chuan hoa
e_v1 = v1/np.linalg.norm(v1) 
e_v2 = v2/np.linalg.norm(v2) 
e_v3 = v3/np.linalg.norm(v3) 
print(e_v1, e_v2, e_v3, sep="\n")

# Tim hinh chieu truc giao
y = np.array([3, -3, 7, -5])
print(f"Hình chiếu trực giao của {y} là: ")
y_proj = np.inner(y, e_v1) * e_v1 + np.inner(y, e_v2) * e_v2 + np.inner(y, e_v3) * e_v3
print(y_proj)
z = y - y_proj
print(np.around(np.inner(z, y_proj),5))



[0.5 0.5 0.5 0.5]
[-0.81649658  0.40824829  0.40824829  0.        ]
[-0.0758098  -0.75809804  0.60647843  0.22742941]
Hình chiếu trực giao của [ 3 -3  7 -5] là: 
[ 0.77586207 -3.74137931  3.29310345  1.67241379]
0.0


In [43]:
# Tim phan tich QR
A = np.array([[1, 0, 0],
              [1,1,0],
              [1,1,1]])
print(A)
x1 = A[:,0]
x2 = A[:,1]
x3 = A[:,2]

# Thuc hien thuat toan gram schmidt
v1 = x1
v2 = x2 - np.inner(x2, v1)/np.inner(v1, v1) * v1
v3 = x3 - np.inner(x3, v1)/np.inner(v1, v1) * v1 - np.inner(x3, v2)/np.inner(v2, v2) * v2


# Kiem tra bang cach tinh tich tung doi mot, neu tat ca = 0 thi dung.
# Truc chuan hoa
e_v1 = v1/np.linalg.norm(v1) 
e_v2 = v2/np.linalg.norm(v2) 
e_v3 = v3/np.linalg.norm(v3) 
print("Co so cua khong gian Col(A) la ")
print(e_v1, e_v2, e_v3, sep="\n")

# Ma tran truc giao Q
Q = np.vstack([e_v1, e_v2, e_v3]).T
print(Q)

[[1 0 0]
 [1 1 0]
 [1 1 1]]
Co so cua khong gian Col(A) la 
[0.57735027 0.57735027 0.57735027]
[-0.81649658  0.40824829  0.40824829]
[ 0.         -0.70710678  0.70710678]
[[ 0.57735027 -0.81649658  0.        ]
 [ 0.57735027  0.40824829 -0.70710678]
 [ 0.57735027  0.40824829  0.70710678]]


In [46]:
x1_cood = np.array([np.inner(x1, e_v1), np.inner(x1, e_v2), np.inner(x1, e_v3)])
x2_cood = np.array([np.inner(x2, e_v1), np.inner(x2, e_v2), np.inner(x2, e_v3)])
x3_cood = np.array([np.inner(x3, e_v1), np.inner(x3, e_v2), np.inner(x3, e_v3)])
R = np.vstack([x1_cood, x2_cood, x3_cood]).T
print(R)
# Kiem tra
np.allclose(A, Q@R)

[[1.73205081e+00 1.15470054e+00 5.77350269e-01]
 [1.11022302e-16 8.16496581e-01 4.08248290e-01]
 [0.00000000e+00 0.00000000e+00 7.07106781e-01]]


True

In [48]:
# Su dung lenh np.linalg.qr()
Q, R = np.linalg.qr(A)
print(Q)
print(R)

[[-5.77350269e-01  8.16496581e-01 -8.75605293e-17]
 [-5.77350269e-01 -4.08248290e-01 -7.07106781e-01]
 [-5.77350269e-01 -4.08248290e-01  7.07106781e-01]]
[[-1.73205081 -1.15470054 -0.57735027]
 [ 0.         -0.81649658 -0.40824829]
 [ 0.          0.          0.70710678]]
