## Giới thiệu về thư viện Numpy

In [2]:
import numpy as np

In [20]:
A = np.array([[1,2,3], [2,-4,1]])
print('A = ', A, sep="\n")

A = 
[[ 1  2  3]
 [ 2 -4  1]]


In [24]:
print(A.ndim)
print(A.shape)
print(A.size)

2
(2, 3)
6


In [28]:
# Một số cách khởi tạo khác
A1 = np.zeros(5)
A1

array([0., 0., 0., 0., 0.])

In [3]:
np.array([1,2])

array([1, 2])

In [4]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.linspace(1,10,20)
A6 = np.random.random((2,2))
print(A6)
np.random.randint(1,15,(2,3))
np.random.normal(0,9,(3,2))
np.random.randn(7)
np.eye(3)

[[0.25564797 0.0642546 ]
 [0.12629953 0.91928048]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
v1 = np.array([1, 2, -2, 3])
v2 = np.array([-2,5,1,7])
v3 = np.arange(4)
v = np.vstack([v1, v2, v3])
print(v)
u1 = v1[:, np.newaxis]
print(u1)

[[ 1  2 -2  3]
 [-2  5  1  7]
 [ 0  1  2  3]]
[[ 1]
 [ 2]
 [-2]
 [ 3]]


In [20]:
A = np.random.randn(100)
print(A)
A.mean()

[ 2.1530905  -1.37289577 -0.723153   -0.57225256  0.13926936 -1.28801573
  1.30248543  1.41738952  0.29158684  0.43876992 -0.13151058 -0.52762665
  0.10889508  0.44265998  2.32663267 -0.48451461 -1.8031845  -1.26925587
 -0.33433779 -0.45579391 -0.00844683 -0.709205    0.28117713 -0.07222447
 -0.6813844  -2.13584871  1.23505643  0.3927822   0.56002407 -1.51216695
  1.29049736  0.58309593 -0.74490399  1.20745721  0.6579713  -0.35274931
  0.45698561  1.81731093  0.90184447  1.5684633  -0.33882493 -0.2130519
 -1.24623705  1.30148155 -0.69641622  0.02459788  0.94834722  0.47104108
  0.23442869 -0.17854131 -0.71678961  0.01863943  1.24084403  0.93518078
  0.34704826  0.48356871  0.45679464 -2.55748837  0.02931142  1.12108455
 -0.70489338  1.36328979 -1.12310507 -0.6337052   0.51251331 -1.28164846
 -0.00626517  0.39603192 -0.40221654  0.04399509  1.26269058 -0.6386931
  0.73811944 -0.16630852  0.63929402  1.2572447  -0.51811024 -0.63069925
  0.62887837 -0.66200726 -0.37828077 -0.51254607 -0.0

0.09453800972661233

In [38]:
# Bai 1
A = np.random.randint(-10, 10, (10, 10))
A[:,0] = A[0, 0]
A[:,9] = A[0, 9]
for row in range(1, 10):
    for col in range(1,9):
        A[row, col] = (A[row - 1, col - 1] + A[row - 1, col] + A[row - 1, col + 1]) / 3
print(A)

[[-8 -6  5  2  6  5  7  0 -3  5]
 [-8 -3  0  4  4  6  4  1  0  5]
 [-8 -3  0  2  4  4  3  1  2  5]
 [-8 -3  0  2  3  3  2  2  2  5]
 [-8 -3  0  1  2  2  2  2  3  5]
 [-8 -3  0  1  1  2  2  2  3  5]
 [-8 -3  0  0  1  1  2  2  3  5]
 [-8 -3 -1  0  0  1  1  2  3  5]
 [-8 -4 -1  0  0  0  1  2  3  5]
 [-8 -4 -1  0  0  0  1  2  3  5]]


In [51]:
# Bai 2
x = np.arange(10)
f1 = x + 3
f2 = x + 5
f3 = x + 6
f1 = f1[:, np.newaxis]
x = x[:, np.newaxis]
f2 = f2[:, np.newaxis]
f3 = f3[:, np.newaxis]
f = np.hstack([x, f1, f2, f3])
print(x)
print(f)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[ 0  3  5  6]
 [ 1  4  6  7]
 [ 2  5  7  8]
 [ 3  6  8  9]
 [ 4  7  9 10]
 [ 5  8 10 11]
 [ 6  9 11 12]
 [ 7 10 12 13]
 [ 8 11 13 14]
 [ 9 12 14 15]]


In [52]:
f.T

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])